part1: part1.cpp
	g++ part1.cpp
	./a.out input.ppm output_part1.ppm
	echo "Finished Running part1.cpp. Please find output in output_part1.ppm"
part2_1a: part2_1a.cpp
	g++ part2_1a.cpp -lpthread
	./a.out input.ppm output_part2_1a.ppm
	echo "Finished Running part2_1a.cpp. Please find output in output_part2_1a.ppm"
part2_1b: part2_1b.cpp
	g++ part2_1b.cpp -lpthread
	./a.out input.ppm output_part2_1b.ppm
	echo "Finished Running part2_1b.cpp. Please find output in output_part2_1b.ppm"
part2_2: part2_2.cpp
	g++ part2_2.cpp -lpthread
	./a.out input.ppm output_part2_2.ppm
	echo "Finished Running part2_2.cpp. Please find output in output_part2_2.ppm"
part2_3: part2_3.cpp
	g++ part2_3.cpp -lpthread
	./a.out input.ppm output_part2_3.ppm
	echo "Finished Running part2_3.cpp. Please find output in output_part2_3.ppm"
clean:
	rm -rf a.out a.exe