part1: part1.cpp
	g++ part1.cpp
	./a.out input.ppm output_part1.ppm
	echo "Finished Running part1.cpp. Please find output in output_part1.ppm"
part2_1a: part2_1a.cpp
	g++ part2_1a.cpp -lpthread
	./a.out input.ppm output_part2_1a.ppm
	echo "Finished Running part2_1a.cpp. Please find output in output_part2_1a.ppm"
clean:
	rm -rf a.out a.exe